# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"find_binary_clf_threshold": "ml.evaluation.ipynb"}

modules = ["ml/evaluation.py"]

doc_url = "https://bdsaglam.github.io/fastnote/"

git_url = "https://github.com/bdsaglam/fastnote/tree/master/"

def custom_doc_links(name): return None
